lanl-ansi/PowerModelsDistribution.jl

src/io/dss_structs.jl, src/io/opendss.jl, test/data/opendss/test2_linecodes.dss, test/data/opendss/test2_master.dss, test/data/opendss/test_simple2.dss, test/data/opendss/test_simple3.dss, test/data/opendss/test_simple4.dss, test/opendss.jl
Adds support for the "like" keyword in OpenDSS. Adds unit tests and
new components to `test2_master.dss`.
Closes #38
=> ADD: Support for "like" in OpenDSS

src/form/acp.jl
Refactored ACP on_off constraints to complete refactor of ohms constraint
equations.
Closes #29
=> REF: Pull diagonal terms out of ohms constraint equations

src/io/dss_structs.jl, src/io/opendss.jl, test/data/opendss/test2_master.dss, test/opendss.jl
Adds a "switch" data field to branches (and transformers, which are set
to false by default)
=> ADD: switch field to branches

CHANGELOG.md, REQUIRE, src/form/bf_mx.jl, src/io/common.jl, src/io/matlab.jl, src/io/opendss.jl, test/tp_opf_bf.jl
The only thing of particular note is that I fixed a bug in the Matlab and OpenDSS parsers where some empty arrays of optional components were note getting turned into empty dicts.
=> Updates for PowerModels v0.9

CHANGELOG.md, src/io/opendss.jl, test/data/opendss/test2_master.dss, test/opendss.jl
Fixes bug with mismatched line lengths where lengths were not getting
converted correctly. Adds unit test.
=> FIX: Line lengths and units

CHANGELOG.md, src/ThreePhasePowerModels.jl, src/form/apo.jl, src/form/dcp.jl, test/tp_opf.jl
This should address #133.  @pseudocubic can you test on internal data?  If something is not working add a broken test to this branch and I'll fix it.
=> Update for Active Power Only Models

CHANGELOG.md, Project.toml, README.md, src/ThreePhasePowerModels.jl
Adds package name depreciation warnings (TPPMs -> PowerModelsDistribution.jl)
Updates to Project.toml to v0.3.2 (final version as TPPMs)
=> ADD: Depreciation warnings, update package version

.travis.yml, CHANGELOG.md, Manifest.toml, Project.toml, test/base.jl, test/data.jl, test/debug.jl, test/loadmodels.jl, test/matlab.jl, test/mld.jl, test/multinetwork.jl, test/opendss.jl, test/opf-var.jl, test/opf.jl, test/opf_bf.jl, test/pf.jl, test/transformer.jl
Updates to use JuMP v0.20, MOI v0.9
Updates travis to use default script, updates to Julia v1.2 tests, and adds Windows
Adds `@info` to each test file to avoid Travis test timeout (no output received in 10m0s)
Updates changelog
=> UPD: JuMP v0.20 / MOI v0.9

src/core/constraint_template.jl, src/core/variable.jl, src/form/acp.jl, src/form/acr.jl
@ccoffrin, is this going in the right direction? More tests are passing.
- parses model and calls ipopt
- returns similar result to ACP
- delta loads / transformers not yet tested
=> Fix for ACR OPF

src/core/variable_mx.jl, src/form/bf.jl, src/form/bf_mx.jl, src/form/shared.jl, src/prob/debug.jl, src/prob/mld.jl, src/prob/opf_bctr.jl, src/prob/opf_bf.jl, src/prob/opf_bf_lm.jl, src/prob/pf_bf.jl
first fixes of BFM forms (KCL vector + matrix) for all load models, including solution builder support
=> Pms v15 matrix forms

src/PowerModelsDistribution.jl, src/core/base.jl, src/core/constraint.jl, src/core/constraint_template.jl, src/core/variable.jl, src/form/acp.jl, src/form/acr.jl, test/opf.jl, test/pf.jl
made progress on pf.jl and opf.jl tests
=> Pms v15 acp

src/core/variable.jl, src/form/shared.jl, src/form/wr.jl
=> Pms v15 socwr

src/core/constraint.jl, src/core/constraint_template.jl, src/core/objective.jl, src/core/ref.jl, src/core/variable.jl, src/form/acp.jl, src/form/apo.jl, src/form/dcp.jl, src/form/shared.jl, src/prob/test.jl, test/multiconductor.jl, test/pf.jl, test/runtests.jl
936 passed, 104 failed, 62 errored, 0 broken
=> Pms v15 mn tests

src/core/constraint.jl, src/core/constraint_template.jl, src/core/variable.jl, src/core/variable_mx.jl, src/form/apo.jl, src/prob/test.jl, test/multiconductor.jl, test/multinetwork.jl, test/runtests.jl
1065 passed, 91 failed, 28 errored, 0 broken.
=> Pms v15 multinetwork

src/core/constraint_template.jl, src/core/solution.jl, src/form/acp.jl, src/form/apo.jl, src/prob/test.jl
1074 passed, 99 failed, 20 errored
=> Pms v15 uc

test/runtests.jl
=> scs solver setting

src/core/constraint_template.jl, src/core/variable.jl, src/form/apo.jl, src/form/shared.jl, src/prob/mld.jl, src/prob/test.jl, test/multiconductor.jl
=> Pms v15 fixes

CHANGELOG.md, docs/src/formulations.md, src/core/data.jl, src/core/variable.jl, src/form/shared.jl, src/form/wr.jl, test/multi-nw-cnd.jl, test/multiconductor.jl, test/runtests.jl
=> Pms v15 bugfixes

src/core/constraint_template.jl, src/form/acp.jl, src/form/acr.jl, src/form/apo.jl, src/form/bf_mx.jl, src/form/bf_mx_lin.jl, src/form/shared.jl, src/io/opendss.jl, test/debug.jl, test/multiconductor.jl, test/opf.jl, test/opf_bf.jl, test/pf.jl, test/runtests.jl
I added theta ref for ACR and ACP
Comparing the results obtained from PM is hard because there are features in the mat files that PMD does not support, such as
- dclines
- bus_type 2
- branch shift/tap
So I decided to comment out those tests altogether after investigating for half a day. I managed to close half of the failing unit tests, but it mostly uncovered differences between PMD and PMs than actual issues in PMD.
=> Pms v15 dcfix

CHANGELOG.md, src/data_model/eng2math.jl, src/data_model/transformations.jl, src/data_model/units.jl, test/data_model.jl
- ADD: added a transformation `rm_bounds!` that removes all fields ending in `_ub` and `_lb`
- FIX: added missing `connections` for virtual generator at voltage source
- FIX: corrected pu conversion bus voltage bounds, and added parsing for `vm_pair_lb` and `vm_pair_ub`
- STY: corrected indent level
=> misc minor changes v0.9.1 sander

CHANGELOG.md, README.md, docs/src/index.md
One to surface the official documentation, one to fix a julia 1.0 install syntax change.
=> Minor Documentation Fixes

CHANGELOG.md, docs/src/manual/formulations.md, src/PowerModelsDistribution.jl, src/core/solution.jl, src/core/types.jl, src/form/bf_fbs.jl, src/form/bf_mx_fbs.jl, test/opf_bf.jl
This adds a forward-backward sweep (FBS) linear unbalanced branch flow formulation. The model is linearized around an initial operating point using a single iteration of the FBS method.
=> ADD: Forward-backward sweep (FBS) linear formulation

CHANGELOG.md, src/data_model/utils.jl, src/form/bf_fbs.jl, src/form/bf_mx_lin.jl, src/form/fotp.jl, src/form/fotr.jl, test/loadmodels.jl
This PR fixes indexing issue for single-phase delta load models used in linear formulations (LinDist3Flow, FOTP, FOTR, FBS).
=> FIX: indexing of single-phase delta loads for linear formulations

CHANGELOG.md, src/core/objective.jl, test/opf.jl
This PR fixes the calculation of polynomial nonlinear costs above quadratic. Non-breaking fix.
=> FIX: implementation of polynomial nl costs above quadratic

CHANGELOG.md, Project.toml, docs/src/reference/base.md, examples/Extension Tutorial.jl, src/core/base.jl, src/core/data.jl, src/core/objective.jl, src/core/solution.jl, src/form/acp.jl, src/form/acr.jl, src/form/bf_fbs.jl, src/form/en_acr.jl, src/form/en_ivr.jl, src/form/en_shared.jl, src/form/fotp.jl, src/form/fotr.jl, src/form/ivr.jl, src/form/utils.jl, test/en_opf_bounds.jl, test/transformer.jl
Closes #453
The tests haven't finished running locally, so there might be some more changes needed, but this is a start. I'll comment in-line about some formatting changes we could do here, or in a separate PR.
=> UPD: update to the NonlinearExpr syntax of JuMP v1.15
