src/form/acp.jl, src/io/dss_structs.jl, src/io/opendss.jl, src/prob/tp_pf.jl, test/data/opendss/case2_diag.dss, test/data/opendss/test_simple.dss, test/opendss.jl, test/tp_pf.jl
Fixes parsing of OpenDSS lines. Units of `rmatrix`, `xmatrix`, `cmatrix`,
`b_fr` and `b_to` were 1/MVA, instead of pu, fixed now. Adds factor 3
to `rmatrix` and `xmatrix`. Refactors handling of `Rg`, `Xg` in
`createLine`.
Fixes bug in bus parsing; vmin and vmax were being overwritten in the
for-loop, changed variable names to fix this.
Adds unit tests to ensure better parity with results of OpenDSS. Adds
new 2-bus test with only diagonal elements in `rmatrix` and `xmatrix`.
Tightens tolerances on existing unit test on 3-bus balanced and
unbalanced cases. Adjusts simple test case to move generator from
sourcebus to bus 2.
Fixes a typo in `src/prob/tp_pf.jl` that was causing PowerFlow problems
based on OpenDSS data to fail.
Adds new powerflow tests based on OpenDSS data.
=> FIX: OpenDSS Parser, PowerFlow Problem

src/core/constraint_template.jl, src/core/ref.jl, src/core/variable.jl, src/form/acp.jl, src/form/bf.jl, src/form/dcp.jl, src/form/shared.jl, src/form/wr.jl, src/io/matlab.jl, src/io/opendss.jl, src/prob/tp_opf.jl, src/prob/tp_opf_bf.jl, src/prob/tp_ots.jl, src/prob/tp_pf.jl, test/data/matlab/case5.m, test/matlab.jl, test/opendss.jl, test/runtests.jl, test/tp_opf.jl, test/tp_opf_bf.jl, test/tp_ots.jl, test/tp_pf.jl
An update that works with https://github.com/lanl-ansi/PowerModels.jl/pull/324
@pseudocubic, please review.  Especially if I did the OpenDSS part correctly.
In terms of temp variables I changed `h` to `c` and `g` to `d`.
Once you are happy with this, squash merge the PowerModels PR and this one.
=> Multi-conductor Rename

test/data/opendss/case3_balanced.dss, test/data/opendss/case3_unbalanced.dss, test/opendss.jl
Updates case3_{un}balanced unit tests to be more tight based on the
updates in PR #66.
Adds `defaultbasefreq=50` to case files to enforce the frequency being
solved.
Changed `kv` of the loads to be `( 0.4 3 sqrt / )`.
=> UPD: case3 unit test updates

src/io/dss_structs.jl, test/data/opendss/case3_balanced_isc.dss
solving issue #86 
corrected two typos (isc1=>kwargs) and added a version of case3_balanced.dss that specifies ISC1 and ISC3 instead of MVAsc1 and MVAsc3, which revealed this bug in the first place
=> typo fix in dss_structs.jl

src/io/opendss.jl
Updated `pmin` to be 0% instead of 30% when parsing generators from
OpenDSS. No real-power minimum is defined by OpenDSS spec.
=> UPD OpenDSS generator parser

.travis.yml
Updates .travis.yml to be more consistent with current PowerModels.jl 
style, and fixes the problem with test timeouts.
Adds Julia v0.7/1.0 tests (with allowed failures) to prepare for 
upcoming v0.7/v1.0 julia compatibility update.
=> FIX Travis test failure

CHANGELOG.md, src/io/dss_parse.jl, test/data/opendss/test_transformer_formatting.dss, test/opendss.jl
In opendss `~` indicates continuation of previous line, but in cases
where whitespace preceeded the `~` character, that character was
inserted into the parsed data (in the specific case where this was
discovered, into the `phases` data field of a transformer. The order
of the `strip` commands was changed to `strip(strip(line), "~")` to
solve this problem. Unit test is included.
=> FIX: bug in parsing ~ lines with preceeding whitespace

CHANGELOG.md, src/io/opendss.jl, test/opendss.jl
Adds three source id related fields to supported PowerModels components,
including "load", "shunt", "branch" (incl. transformers and starbuses), "gen",
"storage", and "pysystem". Buses do not have such fields because of
their implicit declarations in OpenDSS, with the exception of starbuses,
who originate from 3-winding transformers. 
Each supported component will contain three new source-related fields:
"source_id" and "active_phases". "source_id" has the format
"source_type.source_name". "active_phases" is represented as a sparse
array, where each active phase number is included, e.g. `[2, 3]` if phases
2 and 3 are active.
The function `parse_dss_source_id(component)` will return a custom struct
with members `dss_type`, `dss_name` and `active_phases` for easy
aggregation of this …
=> ADD: 'source_id' to identify source of PM components from OpenDSS

CHANGELOG.md, src/io/opendss.jl, test/data/opendss/case3_balanced_pv.dss, test/data/opendss/case3_unbalanced_1phase-pv.dss, test/opendss.jl
Adds a section to the `dss2tppm_gen!` function to parse PVSystem OpenDSS objects into simple generators as a first approximation. Uses exclusively the `kVA` property to determine the generator limits `pmin/pmax` and `qmin/qmax`, i.e. `0/kVA` and `-kVA/kVA`, respectively.
Added unit test assumes more generation than necessary from PV, and therefore power is expected to be injected back into the sourcebus generator (transmission network).
There are several supported OpenDSS properties for PVSystems that might be more appropriate, and I welcome discussion on the best practice to get the closest approximation to what OpenDSS might be doing. 
In particular, `Pmpp` (Power at the max power point, kW @ 1 kW/m2 of irradiation) seems like it might be a better value to determine `pmax`. As a first …
=> ADD: OpenDSS PVSystem to PM Generators

test/tp_multinetwork.jl
Relaxes multinetwork test tolerances to pass on both PowerModels
v0.8.8 and master after changes in lanl-ansi/PowerModels.jl#418.
Confirmed to pass locally using PowerModels master.
Related to lanl-ansi/PowerModels.jl#420
Closes #107
=> FIX: Relax multinetwork tests

test/tp_opf_bf.jl
Temporarily disables some tp_opf_bf tests for problems with numerical
stability when being testing with JuliaCIBot.
Disables 5-bus coupled meshed AC case and relaxes 5-bus coupled
radial no shut case.
=> FIX: Disables some tests for numerical instability

REQUIRE, src/io/matlab.jl
row_to_typed_dict function used in matlab format file parsing now
resides in InfrastructureModels instead of PowerModels.
=> FIX: Updates to row_to_typed_dict in InfrastructureModels.jl

CHANGELOG.md, src/io/opendss.jl, test/data/opendss/test2_master.dss, test/opendss.jl
OpenDSS allows for a sourcebus to not be called `sourcebus` by using the `bus1` kwarg on `circuit`.
Updates unit tests and changelog
=> FIX: Arbitrary sourcebus names

CHANGELOG.md, src/io/opendss.jl, test/data/opendss/case3_balanced_cap.dss, test/opendss.jl, test/tp_opf.jl
Currently there are two bugs in the parsing of capacitors
- The base should be adjusted as before
- The sign is wrong. The power reference in OpenDSS is expressed in generator sign convention, but the parser  assumes load convention. This can be seen by observing that a capacitor creates a voltage drop instead of a voltage rise.
A unit test will follow later, as part of the matrix line charging parameters.
=> capacitor bug fix

CHANGELOG.md, src/io/dss_structs.jl, test/data/opendss/case3_balanced_switch.dss, test/data/opendss/test2_master.dss, test/opendss.jl, test/pf.jl
In OpenDSS, the `switch=y` property results in `length=0.001` and `units=none`.
Fixing these values results in the correct voltages across the buses, but not the correct power, which I believe must be due to a different power balance constraint being applied than lines have in OpenDSS. This issue is already covered by #156
Changelog and unit tests updated.
=> FIX: OpenDSS switch parsing

CHANGELOG.md, src/io/dss_structs.jl, test/data/opendss/ut_trans_3w_dyy_3_loadloss.dss, test/opendss.jl, test/transformer.jl
Fixes the handling of `%rs` and `%loadloss` properties on OpenDSS transformers.
For 3-winding transformers:
`%loadloss = sum(%rs[1:2])`
`%rs = [%loadloss/2, %loadloss/2, 0.2]`
For 2-winding transformers, `%rs = fill(%loadloss / 2, 2)`
The default value `%r = 0.2` is corrected (was `0.0`)
Because the of the new default values, the number of star buses created for 3-winding transformers changes.
Changelog and Unit tests updated
Closes #157
=> FIX: OpenDSS transformer %rs and %loadloss handling

CHANGELOG.md, src/io/dss_structs.jl, src/io/opendss.jl, test/data/opendss/case3_balanced_basefreq.dss, test/pf.jl
When lines / linecodes do not have the basefreq property, internally the basefreq was previous set to 60 Hz, even if the circuit basefreq is e.g. 50 Hz.
This fix changes this behavior so that if basefreq is not given on a line or linecode, the basefreq for that line is the circuit level basefreq.
The default basefreq for the circuit is still 60 Hz if `set defaultbasefreq` is not used; a warning is given if this command is missing.
Updates unit tests and changelog
Closes #159
=> FIX: Wrong setting of basefreq on lines / linecodes (OpenDSS)

CHANGELOG.md, src/core/export.jl, src/io/opendss.jl, test/data/opendss/case5_phase_drop.dss, test/data/opendss/virtual_sourcebus.dss, test/loadmodels.jl, test/opendss.jl, test/opf.jl, test/pf.jl, test/transformer.jl
In OpenDSS circuits connections to the sourcebus have some impedance. PowerModelsDistribution did not model this, but instead relied on cases have a very stiff source.
To resolve this, the OpenDSS parser creates a virtual sourcebus and a virtual branch with the impedance given by the circuit definition connecting to the sourcebus. The virtual sourcebus is now the reference bus in order to correctly match OpenDSS's output.
The sourcebus generator (sourcegen) has been moved to the virtual sourcebus, as it was an approximation of OpenDSS's vsource at the sourcebus and should be behind the circuit impedance.
Test Changes Notes
- For a couple cases in PF tests against pg / objective were removed, because to compare directly against OpenDSS we primarily use voltages, as that is where direct …
=> ADD: virtual branch to sourcebus to model circuit impedance

CHANGELOG.md, src/io/common.jl, src/io/opendss.jl, test/data/opendss/ut_trans_2w_yy_bank.dss, test/transformer.jl
Adds the ability to utilize the "bank" property on OpenDSS transformers. If the bank property is present, by default the OpenDSS parser will attempt to combine those transformers that have been banked by using their active phases to combine their properties into a single transformer with the "bank" property as its name.
"bank_transformers" kwarg added to `parse_file` to allow users to disable automatic banking of the transformers.
Logic of initial transformer parsing is updated to support this feature.
Added unit test to confirm that automatic banking and no banking result in the same power flow solutions.
Updated changelog.
=> ADD: Parsing of "bank" property on transformers

CHANGELOG.md, src/io/dss_parse.jl, src/io/opendss.jl, test/data/opendss/case3_unbalanced_assym_swap.dss, test/pf.jl
In OpenDSS, the order of phases can be swaped on lines, e.g. `bus1=a.1.2.3 bus2=b.1.2.3` vs `bus1=a.3.2.1 bus2=b.3.2.1`. This has the effect of reordering the line property matrices, i.e. `rmatrix`, `xmatrix`, and `cmatrix`.
This PR accounts for this change by obtaining the phase connections in the order that they appear and reordering the matrices accordingly.
Adds a unit test and updates changelog
=> FIX: phase order swap on lines

CHANGELOG.md, docs/src/specifications.md, src/core/constraint_template.jl, src/core/ref.jl, src/core/variable.jl, src/form/acp.jl, src/form/apo.jl, src/form/bf.jl, src/form/dcp.jl, src/io/opendss.jl, src/prob/debug.jl, src/prob/mld.jl, src/prob/opf.jl, src/prob/opf_bctr.jl, src/prob/opf_lm.jl, src/prob/opf_oltc.jl, src/prob/pf.jl, src/prob/pf_lm.jl, src/prob/test.jl, test/opendss.jl, test/transformer.jl
For consistency with "branch", rename instances of :trans in ref and "trans" in data dictionary to :transformer and "transformer", respectively.
Also renames constraint and variable functions for same consistency.
Internal variables, i.e. those used inside functions, are not changed, and neither are filenames, as both of these should be largely invisible to users.
Updates changelog
=> REF: Rename :trans, "trans", _trans_ to 'transformer'

CHANGELOG.md, src/io/dss_parse.jl, src/io/dss_structs.jl, src/io/opendss.jl, test/data/opendss/case3_balanced_prop-order.dss, test/opendss.jl
In OpenDSS, properties are applied to their respective objects in the order they are written, which means `linecode=x, r0=1` is different than `r0=1 linecode=x`, but until now PowerModelsDistribution applied properties in a fixed order of, `like` then `linecode`, overwriting properties that shouldn't have been overwritten.
Adds additional parsing functions to make this possible. In `parse_dss`, the order properties are entered is now retained in `"prop_order"`, which is used during the conversion to the internal data format.
In OpenDSS, `like` should be applied at the beginning of a line, but its application doesn't seem consistent with the manual, so if it is not
one of the first properties given, a warning is thrown by PowerModelsDistribution that PMD will treat the `like` property as …
=> FIX: apply OpenDSS properties in order written

CHANGELOG.md, src/io/dss_structs.jl, test/data/opendss/test_simple.dss, test/data/opendss/test_simple3.dss, test/data/opendss/test_simple4.dss, test/opendss.jl
Fixes the creation of vsource from circuit to use correct values for mvasc3,mvasc1 and isc3,isc1  if one of the pair is not specified.
Default values in documentation are not consistent with software for ISC(1|3)
Updates unit tests and changelog
Closes #176
=> FIX: setting source values

CHANGELOG.md, src/core/constraint_template.jl, src/core/objective.jl, src/form/acp.jl, src/form/acr.jl, src/form/apo.jl, src/form/dcp.jl, src/form/shared.jl, src/form/wr.jl, src/io/dss_parse.jl, src/io/dss_structs.jl, src/io/opendss.jl, src/prob/debug.jl, src/prob/mld.jl, src/prob/opf.jl, src/prob/opf_bctr.jl, src/prob/opf_bf.jl, src/prob/opf_lm.jl, src/prob/opf_oltc.jl, src/prob/pf.jl, src/prob/pf_bf.jl, src/prob/pf_lm.jl, src/prob/test.jl, test/mld.jl, test/multinetwork.jl, test/opf.jl, test/opf_bf.jl, test/test.jl
Changes to PowerModels v0.13 style of `constraint_power_balance` to make it more generic, including all types of components, and therefore making it more robust to various network compositions.
Removes DC-lines (no such network components yet defined for distribution networks in this package).
Merges storage into main opf and mld problems.
Removes some unused functions.
Removed 4 tests using 3-bus matpower file, due to precense of dclines.
Updates changelog.
=> REF: Make constraint_mc_power_balance generic

CHANGELOG.md, src/core/constraint_template.jl, src/core/ref.jl, src/core/variable.jl, src/form/shared.jl, src/prob/debug.jl, src/prob/mld.jl, src/prob/opf.jl, src/prob/opf_bctr.jl, src/prob/opf_bf.jl, src/prob/opf_lm.jl, src/prob/opf_oltc.jl, src/prob/pf.jl, src/prob/pf_bf.jl, src/prob/pf_lm.jl, src/prob/test.jl, test/multinetwork.jl
Removes any loops over conductors from the problem definitions to avoid confusing users. Loops over conductors, if needed, will happen inside of functions in `src/core/constraint_templates.jl` or `src/core/variables.jl`, particularly for those constraints/variables which merely call back to PowerModels.
Adds the following functions:
- `constraint_mc_storage_loss`
- `constraint_mc_storage_thermal_limit`
- `constraint_mc_thermal_limit_from`
- `constraint_mc_thermal_limit_to`
- `constraint_mc_voltage_magnitude_setpoint`
- `constraint_mv_active_gen_setpoint`
- `variable_mc_generation`
- `variable_mc_generation_on_off`
Fixes a multinetwork bug in `ref_add_arcs_trans!`
Adds an `AbstractWModels` version of `constraint_mc_power_balance`
Fixes multinetwork calls in constraint templates and …
=> REF: Remove loops over conductors from prob

CHANGELOG.md, src/core/data.jl, src/core/solution.jl, src/form/acp.jl, src/form/apo.jl, src/form/dcp.jl, src/form/shared.jl, src/form/wr.jl, src/prob/opf_bf.jl, src/prob/pf_bf.jl, test/pf.jl
Adds unit test that covers `pf_bf` and solution builders with `branch_flow` and `original_variables` options enabled.
Fixes bugs in solution builders where depreciated kwargs were used in `add_setpoint!`.
Removes unused functions that don't seem to have any future purpose.
Specifically, removes `constraint_mc_ohms_yt_on_off` variants, since we have gone in a different direction since these were introduced and OTS spec was removed.
Updates changelog and adds unit test
=> FIX: Branch flow solution building

CHANGELOG.md, src/core/data.jl, src/io/dss_parse.jl, src/io/opendss.jl, test/data.jl
Adds a function to count the number of nodes in a system, `count_nodes`.
Also exposes `find_bus` and `find_component` functions for export (previous only internal functions), to improve the user experience.
Adds unit tests and updates changelog
=> ADD: count_nodes

CHANGELOG.md, src/io/opendss.jl, test/opf.jl
Because the sourcebus is a voltage source with an internal impedance
that we model as a virtual sourcebus connected to a virtual branch
connected to the real sourcebus, the virtual sourcebus should have
a fixed voltage.
To remedy this, `vmin` and `vmax` at the virtual_sourcebus are fixed
to `vm`, i.e. `vmin==vmax==vm`.
Only three OPF test cases needed to be updated, and none of the
voltages in those test cases needed to change:
- 2-bus diagonal acp opf
- 3-bus balanced acp opf
- 3-bus unbalanced isc acp opf
Updates unit tests and changelog
Closes #246
=> FIX: Voltage at virtual_sourcebus should be fixed

CHANGELOG.md, src/io/dss_parse.jl, src/io/opendss.jl, test/opendss.jl
Adds automatic parsing of buscoords (if present) into the PMD data
structure, under the fields `lon` and `lat`.
Adds unit test using existing opendss test files and updates changelog.
Removes `buscoords.dat` from test data files, it does not seem to
be used.
Closes #245
=> ADD: Buscoord parsing into PMD data structure

CHANGELOG.md, src/core/constraint_template.jl, src/form/acp.jl, src/form/acr.jl, src/form/apo.jl, src/form/bf_mx.jl, src/form/bf_mx_lin.jl, src/form/dcp.jl, src/form/shared.jl
These additions store references of `:lam_kcl_r` and `:lam_kcl_i` into `con`.
=> ADD: Store references for power balance constraints.

CHANGELOG.md, docs/Project.toml, docs/make.jl, src/core/data.jl, src/data_model/eng2math.jl, test/data.jl
Currently, the connections/terminals lists that appear on virtual components that are
constructed in the conversion from the ENGINEERING to the MATHEMATICAL data model 
are not consistent, as they haven't yet been actively used.
This PR fixes this consistency issues for the terminals/grounding on virtual buses and connections, _i.e._ `f_connections` and `t_connections`, on virtual branches, consistent for all components that create them (`switch`, `transformer`, and `voltage_source`, currently).
This PR also adds two helper functions to aid in counting the number of active
un-grounded terminals on buses and active un-grounded connections on edge 
components to aid in the evaluation of whether a network is radial:
- `count_active_terminals`
- `count_active_connections`
Both added functions …
=> FIX: Consistency of connections on `MATHEMATICAL` model components

CHANGELOG.md, src/form/acr.jl, test/transformer.jl
As pointed out in #285 , the functions that add the transformer constraints for the ACR formulation are missing. I added these and added unit tests for ACR transformers.
Closes #285
=> ADD: acr transformer constraints

CHANGELOG.md, src/prob/mld.jl, test/mld.jl
Depreciates the `run_mc_mld_bf` function, as was done with the opf
branch flow variants in v0.9. This function was missed during that
refactor, so this PR will depreciate it as to make it a non-breaking
change, and we will plan to remove it in the next breaking release.
=> REF: Depreciate run_mc_mld_bf

.github/workflows/pr_checks.yml, CHANGELOG.md, examples/engineering_model.ipynb, src/core/data.jl, src/data_model/components.jl, src/data_model/eng2math.jl, src/data_model/transformations.jl, src/data_model/utils.jl, src/io/common.jl, src/io/dss_structs.jl, src/io/opendss.jl, src/io/utils.jl, test/data_model.jl, test/opendss.jl, test/transformer.jl
This PR refactors the kron reduction and padding transformations from within the individual eng2math conversion functions into their own functions inside of `src/data_models/transformations.jl` so that they can be applied to the engineering data model separately. This is in preparation for the addition of explicit 4-wire support to be added in v0.10.0.
In order to maintain backwards compatibility for the remainder of v0.9, the kron reduction and padding transformations are automatically applied during the call of the `eng2math` functions, and therefore during `transform_data_model`. This automatic transformation is expected to be removed at a future date. Furthermore, the user will not see the engineering data model after these transformations have been applied (unless they are invoked …
=> REF: extract kron reduction, phase projection from eng2math

CHANGELOG.md, src/io/opendss.jl, test/data/opendss/test2_master.dss, test/opendss.jl
The syntax for adding a ground by default to generation type dss
objects was incorrect, and have been changed to match the syntax
on `generator` objects such that objects have awaiting ground
added automatically by default in such a way that multiple grounds
don't get added to the bus which causes problems with kron reduction.
=> FIX: connections on generation type components

CHANGELOG.md, src/form/ivr.jl
`sol(pm, nw, :gen, id)[:cig_bus] = var(pm, nw, :crg_bus, id)` corrected to `sol(pm, nw, :gen, id)[:cig_bus] = var(pm, nw, :cig_bus, id)`
Should I make an entry in the changelog for this very small fix?
=> FIX: typo on line 548 of form/ivr.jl

CHANGELOG.md, src/core/variable.jl, test/opf.jl
- The purpose of this PR is to fix the bug in the assignment of variables' start values to active connections and closes #318 .
For this purpose, _get_conductor_indicator is added and called in  comp_start_value , both to be found in core/variable.jl.  It wasn't possible to reduce _get_conductor_indicator to a ternary operator, because there are more than two different active connections keys: "terminals" (for buses), "connections" (for loads and gens), and "f_connections" and "t_connections" for branches. In the case of branches, "f_connections" are chosen because, as far as I can see, assigning start values to branch variables corresponds to assigning start values to their "from" configuration.
- A test is added in test/opf.jl : it checks that the variable assignment doesn't interfere …
=> FIX: variables start value iteration per active connection (#318)

CHANGELOG.md, src/io/dss_parse.jl, test/data/opendss/test2_edit.dss, test/data/opendss/test2_master.dss, test/opendss.jl
When parsing the dss edit commands, "prop_order" was getting overwritten
by the new object, instead of the "prop_order" getting appended to. This
fixes that problem, and now all previously parsed properties should
appear in the final parsed object.
Adds unit test and updates changelog.
=> FIX: bug in parsing of dss edit command

CHANGELOG.md, Project.toml, examples/engineering_model.ipynb, examples/engineering_model_helper_functions.ipynb, src/prob/common.jl, src/prob/debug.jl, src/prob/mld.jl, src/prob/opf.jl, src/prob/opf_oltc.jl, src/prob/osw.jl, src/prob/pf.jl, src/prob/test.jl, test/data_model.jl, test/debug.jl, test/delta_gens.jl, test/loadmodels.jl, test/mld.jl, test/multinetwork.jl, test/opf.jl, test/opf_bf.jl, test/opf_iv.jl, test/pf.jl, test/pf_bf.jl, test/shunt.jl, test/storage.jl, test/switch.jl, test/transformer.jl
`run_` functions are depreciated in favor of `solve_`. Depreciation
warnings will remain for ~4-6 months before being removed
completely.
Updates InfrastructureModels to ~0.5.4 to add support for
`relax_integrality`.
Updates changelog and unit tests
=> REF: depreciate `run_` functions for `solve_`

CHANGELOG.md, src/core/variable_mx.jl, src/form/bf_mx_lin.jl, test/data/opendss/case3_unbalanced_delta_loads.dss, test/opf_bf.jl
This adds the following load models to the LinDist3Flow formulation:
1. Wye-connected, constant current loads
2. Delta connected, constant power/current/impedance loads
=> ADD: Load models for LinDist3Flow

CHANGELOG.md, src/io/dss/dss_data_structs.jl, src/io/utils.jl, test/data/opendss/test2_master.dss, test/opendss.jl
This PR adds initial support for parsing of CapControl and RegControl dss objects in preparation for using them to update transformer and capacitor settings for new problem types in the future.
CC @keatsig
=> ADD: initial support for CapControl, RegControl dss parsing

CHANGELOG.md, docs/src/manual/formulations.md
Updates the docs for `LPUBFDiagModel`, because:
1) `LPUBFFullModel` was mentioned, but there was no reference to what it was, as
2) `LPUBFFullModel` is not supported anymore, and does not exist as alias for the diagonal formulation.
=> DOC: extends `LPUBFDiagModel` description in docs

CHANGELOG.md, src/io/dss/dss2eng.jl
This PR fixes a bug related to `pmult` values being overwritten by `qmult` values in the `_dss2eng_loadshape!(...)` function when running multinetwork tests with loadshapes. The option to add `pmult` and `qmult` as separate csv files was not working correctly. 
Closes #386.
=> FIX: bug in _dss2eng_loadshape function

CHANGELOG.md, src/io/dss/dss_parse.jl, test/data/opendss/case_tabulation.dss, test/opendss.jl
This PR Closes #394. and it is **not** a breaking change.
- [Adding a new test case](https://github.com/lanl-ansi/PowerModelsDistribution.jl/commit/fb8e835337e19e9d1efce75b37a53b9d44b1ecfb) that represents the #394 bug.
- [Adding a new test for the new test case](https://github.com/lanl-ansi/PowerModelsDistribution.jl/commit/707cd972ee6b067ce3f1e61c6f810af5c5b59a8f).
- [Changing space validations](https://github.com/lanl-ansi/PowerModelsDistribution.jl/commit/e41649157dd8dcf3c5eb6ab98987ec8dd69e5985) as discussed in https://github.com/lanl-ansi/PowerModelsDistribution.jl/issues/394#issuecomment-1216697932.
- [Update CHANGELOG.md](https://github.com/lanl-ansi/PowerModelsDistribution.jl/commit/0906d11f348467d05360d1892a9d8789bb50f846).
=> FIX: `parse_file` in `.dss` files with character UTF-8 0x09 (Tabulation)

CHANGELOG.md, src/data_model/eng2math.jl
This PR fixes the bug in `_map_eng2math_bus!()` related to shunts where `bs` was calculated using real component of the admittance instead of the imaginary component.
=> FIX: bug in _map_eng2math_bus! function

CHANGELOG.md, src/data_model/transformations.jl
instead of checking that the bus property is a string
Closes #416
=> FIX: check if bus property is vector

CHANGELOG.md, src/io/dss/dss_parse.jl, test/data/opendss/test2_edit.dss, test/opendss.jl
Fixes a bug where if a property is assigned via the pattern, e.g.,
`load.a1.bus1 = some_bus`
in a file that is different from the one where `load.a1` was defined, the assignment would fail.
Closes #397
=> FIX: property assignment in different file

CHANGELOG.md, src/form/bf_mx.jl, test/opf_bf.jl, test/test_cases.jl
This adds matrix P and Q variables for switches to AbstractUBFModels.
Closes #423
Resolves #352
=> ADD: UBF Matrix Power Variables for Switches

CHANGELOG.md, src/form/bf_mx.jl, src/form/bf_mx_lin.jl, src/form/bf_mx_soc.jl, test/transformer.jl
This PR fixes bug with SOC and LinDist3Flow formulations where diagonal entries of matrix variables were defined with type `Vector{JuMP.VariableRef}` (no information about connections) instead of `JuMP.Containers.DenseAxisArray`, leading to errors when single- or two-phase elements (nodes, lines, switches) were present in network. 
Also, this PR adds loads/generator models which are connected between two secondary terminals (240V devices) of center-tapped transformers for SOC formulation.
=> FIX: SOC and LinDist3Flow formulations for elements with missing phases

src/prob/native_pf.jl
This PR requests adding the arvix reference of the current injection method algorithm implementation to the appropriate docstrings in native_pf.jl file.
The change only adds a few lines in the docstrings and does not add any line of actual code.
=> DOC: add arvix reference to native power flow

CHANGELOG.md, src/io/utils.jl, test/transformer.jl
There is a bug in _bank_transformers! where if a transformer bank has controls, but either has non-sequential phases, e.g., (1, 3) or has phases not starting with 1, e.g., (2,3), then the function would throw an error because the destination conductor index `c` was wrong.
Also fixes occasionally failing test
Resolves #443
=> FIX: transformer control dss2eng

test/pf.jl, test/test_cases.jl
This fixes a minor typo in test_cases.jl and test.pf.jl, where "blanced" should be "balanced". The typo has no negative effect, but is fixed here.
=> FIX: blanced to balanced
